services:
  - type: web
    name: adminsphere-api
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        value: https://temporary-instant-ridge-mw3kmwc.vercel.app
      - key: MONGO_URI
        sync: false
